apiVersion: apps/v1beta2 # for versions before 1.8.0 use apps/v1beta1
kind: StatefulSet
metadata:
  name: gollum
  labels:
    app: gollum
spec:
  serviceName: gollum
  replicas: 3
  selector:
    matchLabels:
      app: gollum
  template:
    metadata:
      labels:
        app: gollum
    spec:
      terminationGracePeriodSeconds: 1800
      containers:
      - name: gollum
        image: quay.io/vellichor/gollum:master
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        lifecycle:
          postStart:
            exec:
              command: 
              - /bin/git-init.sh
        env:
        - name: GOLLUM_GIT_REPO
          value: YOUR_BACKING_REPO_HERE
        resources:
          limits:
            cpu: "500m"
            memory: 1Gi
          requests:
           cpu: "500m"
           memory: 1Gi
        volumeMounts:
        - name: wiki-data
          mountPath: /wiki-data
        - name: git-secret
          mountPath: /git-secret
      volumes:
      - name: git-secret
        secret:
          secretName: gollum-git-secret
  volumeClaimTemplates:
  - metadata:
      name: wiki-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: default
      resources:
        requests:
          storage: 1Gi