kind: Service
apiVersion: v1
metadata:
  name: gollum
spec:
  selector:
    app: gollum
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
#  - name: https
#    protocol: TCP
#    port: 443
#    targetPort: 443
  type: LoadBalancer
#  loadBalancerSourceRanges:
#    - 0.0.0.0/0